[build]
  command = "npm run build"
  publish = ".next"

[context.production]
  command = "npm run build"
  environment = { 
    NEXT_PUBLIC_ENVIRONMENT = "production",
    NODE_ENV = "production"
  }

[context.develop]
  command = "npm run build:staging"
  environment = { 
    NEXT_PUBLIC_ENVIRONMENT = "staging",
    NODE_ENV = "development"
  }

[context.deploy-preview]
  command = "npm run build:staging"
  environment = { 
    NEXT_PUBLIC_ENVIRONMENT = "staging",
    NODE_ENV = "development"
  }

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  SECRETS_SCAN_ENABLED = "false"

# Production-specific environment
[context.production.environment]
  SECRETS_SCAN_ENABLED = "true"

# Netlify CLI development settings
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

# Redirect for Next.js Image Optimization
[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/images"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co"