[build]
  command = "npm run build"
  publish = ".next"

[context.production]
  command = "npm run build"
  environment = { NEXT_PUBLIC_ENVIRONMENT = "production" }

[context.develop]
  command = "npm run build:staging"
  environment = { NEXT_PUBLIC_ENVIRONMENT = "staging" }

[context.deploy-preview]
  command = "npm run build:staging"
  environment = { NEXT_PUBLIC_ENVIRONMENT = "staging" }