[build]
  command = "npm install && npm run build"
  publish = ".next"

[context.production]
  command = "npm install && npm run build"

[context.production.environment]
  NEXT_PUBLIC_ENVIRONMENT = "production"
  NODE_ENV = "production"

[context.develop]
  command = "npm install && npm run build:staging"

[context.develop.environment]
  NEXT_PUBLIC_ENVIRONMENT = "staging"
  NODE_ENV = "production"

[context.deploy-preview]
  command = "npm install && npm run build:staging"

[context.deploy-preview.environment]
  NEXT_PUBLIC_ENVIRONMENT = "staging"
  NODE_ENV = "production"

# Secrets scanning konfiguration
[secrets_scan]
  omit_keys = ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY"]
  omit_paths = [
    ".next/**/*",
    ".netlify/**/*",
    "public/**/*",
    ".env.example"
  ]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/images"
  status = 200